[tool.poetry]
name = "spacy-ru"
version = "0.1.0"
description = ""
authors = ["Yuri Baburov <burchik@gmail.com>"]

[tool.poetry.dependencies]
python = "*"
spacy = "^2.0"
pymorphy2 = "^0.8"
notebook = "^5.6"
pandas = "^0.23.4"

[tool.poetry.dev-dependencies]
pytest = "^3.0"
ipython = "^6.5"
#spacy = { git = "https://github.com/buriy/spaCy.git", branch = "master" }
#cupy = "^4.3"
cupy-cuda91 = "^4.3"

[tool.black]
line-length = 88
target-version = ['py27', 'py35', 'py36']
exclude = '''
(
  /(
      \.eggs
    | \.git
    | \.pytest_cache
    | build
    | dist
  )/
)
'''